name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  formatCheck:
    name: Checks Source Code Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script format:check
